version: "3"

volumes:
  glances:
  influxdb:
  grafana:

services:
  glances:
    image: nicolargo/glances:ubuntu-latest-full
    container_name: glances
    restart: always
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - glances:/glances/conf
    environment:
      - "GLANCES_OPT=-C /glances/conf/glances.conf --export influxdb2"
      - "GLANCES_OPT=-w"
    ports:
      - "61208:61208"
    networks:
      - "grafana_network"

  influxdb:
    image: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    env_file:
      - 'env.influxdb2'
    volumes:
      - influxdb:/var/lib/influxdb
      - ./influxdb2:/etc/influxdb2
    networks:
      - grafana_network

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 8080:3000
    user: "1000"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - grafana_network

networks:
  grafana_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_grafana
